; PlatformIO Project Configuration File
; Each firmware type now has its own project folder and configuration.
; To build/upload, navigate to the specific project folder (e.g., setup_anchor)
; and run 'pio run -t upload'

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = /home/ziayd/UWB-Indoor-Localization_Arduino/DW1000_library
upload_port = /dev/ttyUSB1 
; monitor_speed = 115200 ; Uncomment if needed 